name: uniworkly_v3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  geolocator: ^11.1.0      # konum
  mobile_scanner: ^6.0.2   # QR (veya qr_code_scanner)
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ✅ Riverpod 2.x (uyumlu sürüm)
  flutter_riverpod: 2.6.1
  riverpod: 2.6.1

  equatable: ^2.0.7
  intl: ^0.19.0
  google_fonts: ^6.3.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
