import 'models.dart';

final mockListings = <JobListing>[
  JobListing(
    id: 'j1',
    title: 'Kafe Barista',
    company: 'Latte House',
    startTime: DateTime.now().add(const Duration(hours: 2)),
    endTime: DateTime.now().add(const Duration(hours: 8)),
    price: 1200,
    hourlyPrice: 150,
    applications: 18,
    city: 'İstanbul',
    sector: 'Yiyecek & İçecek',
    mealIncluded: true,
    transportIncluded: false,
    description: 'Yoğun saatlerde kasada ve hazırlıkta destek olacak barista arıyoruz.',
    address: 'Beyoğlu, İstiklal Cd. 50',
    rating: 4.4,
    reviewCount: 86,
  ),
  JobListing(
    id: 'j2',
    title: 'Etüt Öğretmeni',
    company: 'ABC Koleji',
    startTime: DateTime.now().add(const Duration(hours: 26)),
    endTime: DateTime.now().add(const Duration(hours: 32)),
    price: 900,
    hourlyPrice: 180,
    applications: 9,
    city: 'Ankara',
    sector: 'Eğitim',
    mealIncluded: false,
    transportIncluded: true,
    description: 'Lise grubu için akşam etütlerinde soru çözümü.',
    address: 'Çankaya, Atatürk Blv. 10',
    rating: 4.2,
    reviewCount: 123,
  ),
  JobListing(
    id: 'j3',
    title: 'Depo Sayımı',
    company: 'Lojistik AŞ',
    startTime: DateTime.now().add(const Duration(hours: 6)),
    endTime: DateTime.now().add(const Duration(hours: 14)),
    price: 1600,
    hourlyPrice: 200,
    applications: 25,
    city: 'İzmir',
    sector: 'Lojistik',
    mealIncluded: true,
    transportIncluded: true,
    description: 'Gecelik sayım operasyonunda ekip çalışmasına yatkın kişiler.',
    address: 'Bornova OSB',
    rating: 3.9,
    reviewCount: 47,
  ),
  JobListing(
    id: 'j4',
    title: 'Özel Matematik Dersi',
    company: 'Mehmet K.',
    startTime: DateTime.now().add(const Duration(hours: 10)),
    endTime: DateTime.now().add(const Duration(hours: 12)),
    price: 600,
    hourlyPrice: 300,
    applications: 3,
    city: 'İstanbul',
    sector: 'Özel Ders',
    mealIncluded: false,
    transportIncluded: false,
    description: 'TYT-AYT seviyesinde birebir matematik.',
    address: 'Kadıköy',
    rating: 4.8,
    reviewCount: 32,
  ),
];
